### ISSUE TITLE
files not found

### ISSUE THREAD

**Issue by yogeshaggarwals** [mrjoshuap/ansible-leapp#2]
- files/leapp-data20.tar.gz
  - files/leapp-data19.tar.gz
  - files/leapp-data18.tar.gz
  - files/leapp-data17.tar.gz
  - files/leapp-data16.tar.gz
  - files/leapp-data15.tar.gz
  - files/leapp-data14.tar.gz
  - files/leapp-data13.tar.gz
  - files/leapp-data12.tar.gz
  - files/leapp-data11.tar.gz
  - files/leapp-data10.tar.gz
  - files/leapp-data9.tar.gz
  - files/leapp-data8.tar.gz
  - files/leapp-data7.tar.gz
  - files/leapp-data6.tar.gz
  - files/leapp-data5.tar.gz
  - files/leapp-data4.tar.gz
  - files/leapp-data3.tar.gz
  - files/leapp-data2.tar.gz
  - files/leapp-data1.tar.gz

these files are not there.

**Comment by yogeshaggarwals** [comment]
TASK [mrjoshuap.leapp : Extract additional required data files (RPM package changes and repository mappings)] *************************
fatal: [rhel7to8-app00.dev.hbgusa.com]: FAILED! => {"msg": "An unhandled exception occurred while running the lookup plugin 'first_found'. Error was a <class 'ansible.errors.AnsibleLookupError'>, original message: No file was found when using first_found. Use errors='ignore' to allow this task to be skipped if no files are found"}

**Comment by mrjoshuap** [comment]
@yogeshaggarwals You have to download the additional required data file (RPM package changes and RPM repository mapping) attached to the Knowledgebase Article [1] and move it to the 'files' directory in the same directory as the playbook including this role.  I am not able to distribute it.

[1] https://access.redhat.com/articles/3664871
